//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LYY_SnacksWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FavoriteShop
    {
        public int FavoriteID { get; set; }
        public string UserID { get; set; }
        public int ShopID { get; set; }
        public string FavoriteType { get; set; }
        public System.DateTime Time { get; set; }
        public int Number { get; set; }
    
        public virtual Shops Shops { get; set; }
        public virtual Users Users { get; set; }
    }
}
