//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LYY_SnacksWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveWords
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LeaveWords()
        {
            this.WordReply = new HashSet<WordReply>();
        }
    
        public int LeaveID { get; set; }
        public string UserID { get; set; }
        public int ShopID { get; set; }
        public string LeaveContent { get; set; }
        public System.DateTime LeaveTime { get; set; }
    
        public virtual Shops Shops { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WordReply> WordReply { get; set; }
    }
}
