//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LYY_SnacksWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shops
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shops()
        {
            this.FavoriteShop = new HashSet<FavoriteShop>();
            this.LeaveWords = new HashSet<LeaveWords>();
        }
    
        public int ShopID { get; set; }
        public string ShopSn { get; set; }
        public string UserID { get; set; }
        public string ArealdPath { get; set; }
        public int ArealID { get; set; }
        public string ShopName { get; set; }
        public string ShopTel { get; set; }
        public string ShopImg { get; set; }
    
        public virtual Areals Areals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FavoriteShop> FavoriteShop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeaveWords> LeaveWords { get; set; }
        public virtual Users Users { get; set; }
    }
}
