//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LYY_SnacksWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public string UserID { get; set; }
        public string NickName { get; set; }
        public string Password { get; set; }
        public string Image { get; set; }
        public string Sex { get; set; }
        public string phone { get; set; }
        public Nullable<System.DateTime> Addtime { get; set; }
        public Nullable<System.DateTime> Birth { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public Nullable<int> JiFen { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
